name: Release

on: 
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    strategy:
      matrix:
        platform: [ windows-latest, ubuntu-latest ]
    
    runs-on:
      ${{matrix.platform}}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Configure dependencies
        if: runner.os == 'Linux'
        run: sudo apt update && sudo apt install -y build-essential gcc-multilib g++-multilib
      - name: Configure dependencies
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86
          sdk: 8.1
          toolset: 12.0

      - name: Create project
        if: runner.os == 'Linux'
        run: cd src && sudo devtools/bin/vpc /vectronic +game /mksln games
      - name: Create project
        if: runner.os == 'Windows'
        run: cd src;devtools/bin/vpc.exe /vectronic +game /mksln games.sln /2013
      
      - name: Download Steam runtime
        if: runner.os == 'Linux'
        run: |
          cd /
          sudo mkdir valve
          cd valve
          sudo wget http://media.steampowered.com/client/runtime/steam-runtime-sdk_latest.tar.xz
          sudo tar xvf steam-runtime-sdk_latest.tar.xz
          sudo mv steam-runtime-sdk_2013-09-05 steam-runtime

      - name: Build project
        if: runner.os == 'Linux'
        run: |
          sudo bash $STEAM_RUNTIME_PATH/setup.sh --debug --target="i386 amd64" --auto-upgrade
          sudo bash $STEAM_RUNTIME_PATH/setup.sh --release --target="i386 amd64" --auto-upgrade
          cd src && sudo make -f games.mak
        env:
          STEAM_RUNTIME_PATH: /valve/steam-runtime
      - name: Build project
        if: runner.os == 'Windows'
        run: cd src;msbuild vectronic.sln

      - name: Upload product
        uses: actions/upload-artifact@v2
        with:
          name: vectronic
        #  path: game/vectronic/bin
          path: game/vectronic
  
  release:
      needs: build
      runs-on: ubuntu-latest

      steps:
        - name: Download artifact
          uses: actions/download-artifact@v2
          with:
            name: vectronic
          
        - name: Create release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          with:
            tag_name: ${{github.ref}}
            release_name: ${{github.ref}}
            draft: false
            prerelease: false
